### ISSUE TITLE
使用更改dockerfile构建的cuda10镜像编译后无法在cuda10中使用

### ISSUE THREAD

**Issue by miaochunyuan** [PaddlePaddle/Serving#606]
修改了dockerfile中的FROM nvidia/cuda:10.0-cudnn7-devel-centos7构建了cuda10编译镜像，编译安装后运行会出现cuda not found的报错：
`GLOG_v=2 python -m paddle_serving_server_gpu.serve --model servingExport/yolov3_darknet_voc/serving_client --port 9293 --gpu_id 5 
mkdir: cannot create directory 'workdir_5': File exists
CUDA not found, please check your environment or use cpu version by "pip install paddle_serving_server"`
在docker中cuda是可以被找到并且使用的，但是一直有这样的报错

**Comment by barrierye** [comment]
您好，我们会尽快复现一下

**Comment by barrierye** [comment]
您好，可以展示下`ldd $SERVING_BIN`和`ls /dev/ | grep nvidia`的输出吗？

**Comment by miaochunyuan** [comment]
> 您好，可以展示下`ldd $SERVING_BIN`和`ls /dev/ | grep nvidia`的输出吗？

感谢，还是发现了$SERVING_BIN设置的有问题，现在可以正常运行了
