### ISSUE TITLE
使用docker编译得到whl包安装后，启动服务报错CUDA not found

### ISSUE THREAD

**Issue by boceng** [PaddlePaddle/Serving#630]
使用docker编译得到paddle_serving_server_gpu-0.2.2-py3-none-any.whl，在docker外进行安装后，启动服务报错：
CUDA not found, please check your environment or use cpu version by "pip install paddle_serving_server"

但在docker内进行安装并启动服务不会报错，启动结果如下：
```
Use local bin : /paddle/ServingCuda10-1/build/core/general-server/serving
Going to Run Comand
/paddle/ServingCuda10-1/build/core/general-server/serving -enable_model_toolkit -inferservice_path workdir_0 -inferservice_file infer_service.prototxt -max_concurrency 0 -num_threads 10 -port 9493 -reload_interval_s 10 -resource_path workdir_0 -resource_file resource.prototxt -workflow_path workdir_0 -workflow_file workflow.prototxt -bthread_concurrency 10 -gpuid 0 -max_body_size 536870912 
I0100 00:00:00.000000 11626 op_repository.h:65] RAW: Succ regist op: GeneralDistKVInferOp
I0100 00:00:00.000000 11626 op_repository.h:65] RAW: Succ regist op: GeneralReaderOp
I0100 00:00:00.000000 11626 op_repository.h:65] RAW: Succ regist op: GeneralDistKVQuantInferOp
I0100 00:00:00.000000 11626 op_repository.h:65] RAW: Succ regist op: GeneralResponseOp
I0100 00:00:00.000000 11626 op_repository.h:65] RAW: Succ regist op: GeneralTextReaderOp
I0100 00:00:00.000000 11626 op_repository.h:65] RAW: Succ regist op: GeneralTextResponseOp
I0100 00:00:00.000000 11626 op_repository.h:65] RAW: Succ regist op: GeneralInferOp
I0100 00:00:00.000000 11626 op_repository.h:65] RAW: Succ regist op: GeneralCopyOp
I0100 00:00:00.000000 11626 service_manager.h:61] RAW: Service[LoadGeneralModelService] insert successfully!
I0100 00:00:00.000000 11626 load_general_model_service.pb.h:299] RAW: Success regist service[LoadGeneralModelService][PN5baidu14paddle_serving9predictor26load_general_model_service27LoadGeneralModelServiceImplE]
I0100 00:00:00.000000 11626 service_manager.h:61] RAW: Service[GeneralModelService] insert successfully!
I0100 00:00:00.000000 11626 general_model_service.pb.h:1473] RAW: Success regist service[GeneralModelService][PN5baidu14paddle_serving9predictor13general_model23GeneralModelServiceImplE]
I0100 00:00:00.000000 11626 factory.h:121] RAW: Succ insert one factory, tag: FLUID_GPU_ANALYSIS, base type N5baidu14paddle_serving9predictor11InferEngineE
W0100 00:00:00.000000 11626 fluid_gpu_engine.cpp:27] RAW: Succ regist factory: ::baidu::paddle_serving::predictor::FluidInferEngine<FluidGpuAnalysisCore>->::baidu::paddle_serving::predictor::InferEngine, tag: FLUID_GPU_ANALYSIS in macro!
I0100 00:00:00.000000 11626 factory.h:121] RAW: Succ insert one factory, tag: FLUID_GPU_ANALYSIS_DIR, base type N5baidu14paddle_serving9predictor11InferEngineE
W0100 00:00:00.000000 11626 fluid_gpu_engine.cpp:33] RAW: Succ regist factory: ::baidu::paddle_serving::predictor::FluidInferEngine< FluidGpuAnalysisDirCore>->::baidu::paddle_serving::predictor::InferEngine, tag: FLUID_GPU_ANALYSIS_DIR in macro!
I0100 00:00:00.000000 11626 factory.h:121] RAW: Succ insert one factory, tag: FLUID_GPU_ANALYSIS_DIR_SIGMOID, base type N5baidu14paddle_serving9predictor11InferEngineE
W0100 00:00:00.000000 11626 fluid_gpu_engine.cpp:39] RAW: Succ regist factory: ::baidu::paddle_serving::predictor::FluidInferEngine< FluidGpuAnalysisDirWithSigmoidCore>->::baidu::paddle_serving::predictor::InferEngine, tag: FLUID_GPU_ANALYSIS_DIR_SIGMOID in macro!
I0100 00:00:00.000000 11626 factory.h:121] RAW: Succ insert one factory, tag: FLUID_GPU_NATIVE, base type N5baidu14paddle_serving9predictor11InferEngineE
W0100 00:00:00.000000 11626 fluid_gpu_engine.cpp:44] RAW: Succ regist factory: ::baidu::paddle_serving::predictor::FluidInferEngine<FluidGpuNativeCore>->::baidu::paddle_serving::predictor::InferEngine, tag: FLUID_GPU_NATIVE in macro!
I0100 00:00:00.000000 11626 factory.h:121] RAW: Succ insert one factory, tag: FLUID_GPU_NATIVE_DIR, base type N5baidu14paddle_serving9predictor11InferEngineE
W0100 00:00:00.000000 11626 fluid_gpu_engine.cpp:49] RAW: Succ regist factory: ::baidu::paddle_serving::predictor::FluidInferEngine<FluidGpuNativeDirCore>->::baidu::paddle_serving::predictor::InferEngine, tag: FLUID_GPU_NATIVE_DIR in macro!
I0100 00:00:00.000000 11626 factory.h:121] RAW: Succ insert one factory, tag: FLUID_GPU_NATIVE_DIR_SIGMOID, base type N5baidu14paddle_serving9predictor11InferEngineE
W0100 00:00:00.000000 11626 fluid_gpu_engine.cpp:55] RAW: Succ regist factory: ::baidu::paddle_serving::predictor::FluidInferEngine< FluidGpuNativeDirWithSigmoidCore>->::baidu::paddle_serving::predictor::InferEngine, tag: FLUID_GPU_NATIVE_DIR_SIGMOID in macro!
I0100 00:00:00.000000 11626 factory.h:121] RAW: Succ insert one factory, tag: FLUID_CPU_ANALYSIS, base type N5baidu14paddle_serving9predictor11InferEngineE
W0100 00:00:00.000000 11626 fluid_cpu_engine.cpp:25] RAW: Succ regist factory: ::baidu::paddle_serving::predictor::FluidInferEngine<FluidCpuAnalysisCore>->::baidu::paddle_serving::predictor::InferEngine, tag: FLUID_CPU_ANALYSIS in macro!
I0100 00:00:00.000000 11626 factory.h:121] RAW: Succ insert one factory, tag: FLUID_CPU_ANALYSIS_DIR, base type N5baidu14paddle_serving9predictor11InferEngineE
W0100 00:00:00.000000 11626 fluid_cpu_engine.cpp:31] RAW: Succ regist factory: ::baidu::paddle_serving::predictor::FluidInferEngine< FluidCpuAnalysisDirCore>->::baidu::paddle_serving::predictor::InferEngine, tag: FLUID_CPU_ANALYSIS_DIR in macro!
I0100 00:00:00.000000 11626 factory.h:121] RAW: Succ insert one factory, tag: FLUID_CPU_ANALYSIS_DIR_SIGMOID, base type N5baidu14paddle_serving9predictor11InferEngineE
W0100 00:00:00.000000 11626 fluid_cpu_engine.cpp:37] RAW: Succ regist factory: ::baidu::paddle_serving::predictor::FluidInferEngine< FluidCpuAnalysisDirWithSigmoidCore>->::baidu::paddle_serving::predictor::InferEngine, tag: FLUID_CPU_ANALYSIS_DIR_SIGMOID in macro!
I0100 00:00:00.000000 11626 factory.h:121] RAW: Succ insert one factory, tag: FLUID_CPU_NATIVE, base type N5baidu14paddle_serving9predictor11InferEngineE
W0100 00:00:00.000000 11626 fluid_cpu_engine.cpp:42] RAW: Succ regist factory: ::baidu::paddle_serving::predictor::FluidInferEngine<FluidCpuNativeCore>->::baidu::paddle_serving::predictor::InferEngine, tag: FLUID_CPU_NATIVE in macro!
I0100 00:00:00.000000 11626 factory.h:121] RAW: Succ insert one factory, tag: FLUID_CPU_NATIVE_DIR, base type N5baidu14paddle_serving9predictor11InferEngineE
W0100 00:00:00.000000 11626 fluid_cpu_engine.cpp:47] RAW: Succ regist factory: ::baidu::paddle_serving::predictor::FluidInferEngine<FluidCpuNativeDirCore>->::baidu::paddle_serving::predictor::InferEngine, tag: FLUID_CPU_NATIVE_DIR in macro!
I0100 00:00:00.000000 11626 factory.h:121] RAW: Succ insert one factory, tag: FLUID_CPU_NATIVE_DIR_SIGMOID, base type N5baidu14paddle_serving9predictor11InferEngineE
W0100 00:00:00.000000 11626 fluid_cpu_engine.cpp:53] RAW: Succ regist factory: ::baidu::paddle_serving::predictor::FluidInferEngine< FluidCpuNativeDirWithSigmoidCore>->::baidu::paddle_serving::predictor::InferEngine, tag: FLUID_CPU_NATIVE_DIR_SIGMOID in macro!
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0601 13:35:24.102823 11626 pdserving.cpp:109] use configure[workdir_0/infer_service.prototxt] port[9493] instead of flags
I0601 13:35:24.959201 11626 init.cc:66] Init commandline: dummy dummy --fraction_of_gpu_memory_to_use=0.006855 --cudnn_deterministic=True 
I0601 13:35:24.959260 11626 analysis_predictor.cc:84] Profiler is deactivated, and no profiling report will be generated.
I0601 13:35:24.974730 11626 analysis_predictor.cc:833] MODEL VERSION: 1.7.1
I0601 13:35:24.974745 11626 analysis_predictor.cc:835] PREDICTOR VERSION: 1.7.2
I0601 13:35:24.975145 11626 analysis_predictor.cc:440] ir_optim is turned off, no IR pass will be executed
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
I0601 13:35:25.131299 11626 ir_params_sync_among_devices_pass.cc:41] Sync params from CPU to GPU
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [ir_graph_to_program_pass]
I0601 13:35:25.299015 11626 analysis_predictor.cc:462] ======= optimize end =======
I0601 13:35:25.302732 11626 fluid_gpu_engine.h:215] create paddle predictor sucess, path: /paddle/PaddleDetection/paddle/paddleDetection/PaddleDetection/servingExport/faster_rcnn_r101_1x/serving_client
W0601 13:35:25.302754 11626 infer.h:487] Succ load common model[0x20a99540], path[/paddle/PaddleDetection/paddle/paddleDetection/PaddleDetection/servingExport/faster_rcnn_r101_1x/serving_client].
W0601 13:35:25.302768 11626 infer.h:185] Succ load model_data_path/paddle/PaddleDetection/paddle/paddleDetection/PaddleDetection/servingExport/faster_rcnn_r101_1x/serving_client
I0601 13:35:25.302775 11626 infer.h:612] FLGS_logtostderr 1
```
-------------------------------------分割线-----------------------------------------

docker内编译设置有：Dockerfile.gpu.devel下第一行为 FROM nvidia/cuda:10.0-cudnn7-devel-centos7，docker内部cuda版本为CUDA Version 10.0.130，docker外部cuda版本同样为CUDA Version 10.0.130，剩余操作均遵循文档步骤。

请问如何解决，感谢~

**Comment by boceng** [comment]
对了，使用的python3编译得到到whl包

**Comment by bjjwwang** [comment]
docker里面和外面都是什么样的CUDA版本
`env | grep LD_LIBRARY_PATH` 分别能看一下吗

**Comment by barrierye** [comment]
在容器外有使用编译出来的二进制吗？（设置`SERVING_BIN`环境变量）

**Comment by boceng** [comment]
> docker里面和外面都是什么样的CUDA版本
> `env | grep LD_LIBRARY_PATH` 分别能看一下吗

docker内：
cat /usr/local/cuda/version.txt
CUDA Version 10.0.130
env | grep LD_LIBRARY_PATH
LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64

docker外：
cat /usr/local/cuda/version.txt
CUDA Version 10.0.130
env | grep LD_LIBRARY_PATH
输出为空

**Comment by boceng** [comment]
> 在容器外有使用编译出来的二进制吗？（设置`SERVING_BIN`环境变量）

你好，有设置SERVING_BIN，但发现了问题，感谢指出。

**Comment by boceng** [comment]
docker内：

[root@51b8568a2eb0 ~]# ldd $SERVING_BIN
	linux-vdso.so.1 =>  (0x00007ffc99d2c000)
	libpthread.so.0 (0x00007f46ef158000)
	libcudart.so.10.0 => /usr/local/cuda/lib64/libcudart.so.10.0 (0x00007f46eeede000)
	libiomp5.so => /paddle/ServingCuda10-1/build/third_party/install/Paddle/third_party/install/mklml/lib/libiomp5.so (0x00007f46eeb02000)
	libmklml_intel.so => /paddle/ServingCuda10-1/build/third_party/install/Paddle/third_party/install/mklml/lib/libmklml_intel.so (0x00007f46e6b86000)
	libdnnl.so.1 => /paddle/ServingCuda10-1/build/third_party/install/Paddle/third_party/install/mkldnn/lib/libdnnl.so.1 (0x00007f46e56ad000)
	libcrypto.so.10 (0x00007f46e524a000)
	librt.so.1 (0x00007f46e5042000)
	libssl.so.10 (0x00007f46e4dd0000)
	libdl.so.2 (0x00007f46e4bcc000)
	libz.so.1 (0x00007f46e49b6000)
	libbz2.so.1 (0x00007f46e47a6000)
	libm.so.6 (0x00007f46e44a4000)
	libstdc++.so.6 (0x00007f46e419d000)
	libgcc_s.so.1 (0x00007f46e3f87000)
	libc.so.6 (0x00007f46e3bb9000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f46ef374000)
	libgssapi_krb5.so.2 (0x00007f46e396c000)
	libkrb5.so.3 (0x00007f46e3683000)
	libcom_err.so.2 (0x00007f46e347f000)
	libk5crypto.so.3 (0x00007f46e324c000)
	libkrb5support.so.0 (0x00007f46e303c000)
	libkeyutils.so.1 (0x00007f46e2e38000)
	libresolv.so.2 (0x00007f46e2c1e000)
	libselinux.so.1 (0x00007f46e29f7000)
	libpcre.so.1 (0x00007f46e2795000)

docker外：

A@irecog:$ ldd $SERVING_BIN
/home/A/ServingCuda10-1/build/core/general-server/serving: libssl.so.10: version `libssl.so.10' not found (required by /home/A/ServingCuda10-1/build/core/general-server/serving)

/home/A/ServingCuda10-1/build/core/general-server/serving: libcrypto.so.10: version `OPENSSL_1.0.1_EC' not found (required by /home/A/ServingCuda10-1/build/core/general-server/serving)

/home/A/ServingCuda10-1/build/core/general-server/serving: libcrypto.so.10: version `libcrypto.so.10' not found (required by /home/A/ServingCuda10-1/build/core/general-server/serving)

	linux-vdso.so.1 =>  (0x00007ffefbb77000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f23140b6000)
	libcudart.so.10.0 => /usr/local/cuda/lib64/libcudart.so.10.0 (0x00007f2313e3c000)

	libiomp5.so => not found
	libmklml_intel.so => not found
	libdnnl.so.1 => not found

	libcrypto.so.10 (0x00007f23139f7000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f23137ef000)
	libssl.so.10 (0x00007f2313586000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2313382000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f2313168000)
	libbz2.so.1 => /lib/x86_64-linux-gnu/libbz2.so.1 (0x00007f2312f58000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2312c4f000)
	libstdc++.so.6 (0x00007f23128cd000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f23126b7000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f23122ed000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f23142d3000)

发现我docker外面缺失动态库，其中libssl.so.10和libcrypto.so.10是可以在我 /lib/x86_64-linux-gnu/下找到的，但OPENSSL_1.0.1_EC、libiomp5.so、libmklml_intel.so、libdnnl.so.1找不到，请问如何export LD_LIBRARY_PATH可以让它找到动态库。
@wangjiawei04 @barrierye

**Comment by bjjwwang** [comment]
libiomp5.so、libmklml_intel.so、libdnnl.so.1 这三个文件在 SERVER_BIN所在的文件夹里面有吗

如果有可以考虑把那个路径加入到 LD_LIBRARY_PATH

**Comment by barrierye** [comment]
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/paddle/ServingCuda10-1/build/third_party/install/Paddle/third_party/install/mklml/lib/
```

**Comment by barrierye** [comment]
> 请问如何export LD_LIBRARY_PATH可以让它找到动态库。

```
sudo docker cp <container-name>:/paddle/ServingCuda10-1/build/third_party/install/Paddle/third_party/install/mklml /host/path/to/mklml
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/host/path/to/mklml/lib
```

**Comment by boceng** [comment]
问题已解决，再次感谢两位
